// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class btse : Exchange
{
    public btse (object args = null): base(args) {}

    public async Task<object> publicGetApiV23MarketSummary (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV23MarketSummary",parameters);
    }

    public async Task<object> publicGetApiV23Ohlcv (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV23Ohlcv",parameters);
    }

    public async Task<object> publicGetApiV23Price (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV23Price",parameters);
    }

    public async Task<object> publicGetApiV23Orderbook (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV23Orderbook",parameters);
    }

    public async Task<object> publicGetApiV23Trades (object parameters = null)
    {
        return await this.callAsync ("publicGetApiV23Trades",parameters);
    }

    public async Task<object> publicSpotGetApiV32MarketSummary (object parameters = null)
    {
        return await this.callAsync ("publicSpotGetApiV32MarketSummary",parameters);
    }

    public async Task<object> publicSpotGetApiV32Ohlcv (object parameters = null)
    {
        return await this.callAsync ("publicSpotGetApiV32Ohlcv",parameters);
    }

    public async Task<object> publicSpotGetApiV32Price (object parameters = null)
    {
        return await this.callAsync ("publicSpotGetApiV32Price",parameters);
    }

    public async Task<object> publicSpotGetApiV32OrderbookL2 (object parameters = null)
    {
        return await this.callAsync ("publicSpotGetApiV32OrderbookL2",parameters);
    }

    public async Task<object> publicSpotGetApiV32Trades (object parameters = null)
    {
        return await this.callAsync ("publicSpotGetApiV32Trades",parameters);
    }

    public async Task<object> privateGetApiV23UserWallet (object parameters = null)
    {
        return await this.callAsync ("privateGetApiV23UserWallet",parameters);
    }

    public async Task<object> privateGetApiV23UserWalletHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetApiV23UserWalletHistory",parameters);
    }

    public async Task<object> privateGetApiV23UserOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetApiV23UserOpenOrders",parameters);
    }

    public async Task<object> privateGetApiV23UserPositions (object parameters = null)
    {
        return await this.callAsync ("privateGetApiV23UserPositions",parameters);
    }

    public async Task<object> privateGetApiV23UserTradeHistory (object parameters = null)
    {
        return await this.callAsync ("privateGetApiV23UserTradeHistory",parameters);
    }

    public async Task<object> privatePostApiV23Order (object parameters = null)
    {
        return await this.callAsync ("privatePostApiV23Order",parameters);
    }

    public async Task<object> privatePostApiV23UserWalletTransfer (object parameters = null)
    {
        return await this.callAsync ("privatePostApiV23UserWalletTransfer",parameters);
    }

    public async Task<object> privatePostApiV23Leverage (object parameters = null)
    {
        return await this.callAsync ("privatePostApiV23Leverage",parameters);
    }

    public async Task<object> privatePostApiV23PositionMode (object parameters = null)
    {
        return await this.callAsync ("privatePostApiV23PositionMode",parameters);
    }

    public async Task<object> privatePutApiV23Order (object parameters = null)
    {
        return await this.callAsync ("privatePutApiV23Order",parameters);
    }

    public async Task<object> privateDeleteApiV23Order (object parameters = null)
    {
        return await this.callAsync ("privateDeleteApiV23Order",parameters);
    }

}