// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *BtseCore) PublicGetApiV23MarketSummary (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV23MarketSummary", args...)
}

func (this *BtseCore) PublicGetApiV23Ohlcv (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV23Ohlcv", args...)
}

func (this *BtseCore) PublicGetApiV23Price (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV23Price", args...)
}

func (this *BtseCore) PublicGetApiV23Orderbook (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV23Orderbook", args...)
}

func (this *BtseCore) PublicGetApiV23Trades (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicGetApiV23Trades", args...)
}

func (this *BtseCore) PublicSpotGetApiV32MarketSummary (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicSpotGetApiV32MarketSummary", args...)
}

func (this *BtseCore) PublicSpotGetApiV32Ohlcv (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicSpotGetApiV32Ohlcv", args...)
}

func (this *BtseCore) PublicSpotGetApiV32Price (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicSpotGetApiV32Price", args...)
}

func (this *BtseCore) PublicSpotGetApiV32OrderbookL2 (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicSpotGetApiV32OrderbookL2", args...)
}

func (this *BtseCore) PublicSpotGetApiV32Trades (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("publicSpotGetApiV32Trades", args...)
}

func (this *BtseCore) PrivateGetApiV23UserWallet (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetApiV23UserWallet", args...)
}

func (this *BtseCore) PrivateGetApiV23UserWalletHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetApiV23UserWalletHistory", args...)
}

func (this *BtseCore) PrivateGetApiV23UserOpenOrders (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetApiV23UserOpenOrders", args...)
}

func (this *BtseCore) PrivateGetApiV23UserPositions (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetApiV23UserPositions", args...)
}

func (this *BtseCore) PrivateGetApiV23UserTradeHistory (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateGetApiV23UserTradeHistory", args...)
}

func (this *BtseCore) PrivatePostApiV23Order (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostApiV23Order", args...)
}

func (this *BtseCore) PrivatePostApiV23UserWalletTransfer (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostApiV23UserWalletTransfer", args...)
}

func (this *BtseCore) PrivatePostApiV23Leverage (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostApiV23Leverage", args...)
}

func (this *BtseCore) PrivatePostApiV23PositionMode (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePostApiV23PositionMode", args...)
}

func (this *BtseCore) PrivatePutApiV23Order (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privatePutApiV23Order", args...)
}

func (this *BtseCore) PrivateDeleteApiV23Order (args ...interface{}) <-chan interface{} {
   return this.callEndpointAsync("privateDeleteApiV23Order", args...)
}
