<?php

namespace ccxt\async\abstract;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


abstract class btse extends \ccxt\async\Exchange {
    public function public_get_api_v2_3_market_summary($params = array()) {
        return $this->request('api/v2.3/market_summary', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_api_v2_3_ohlcv($params = array()) {
        return $this->request('api/v2.3/ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_api_v2_3_price($params = array()) {
        return $this->request('api/v2.3/price', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_api_v2_3_orderbook($params = array()) {
        return $this->request('api/v2.3/orderbook', 'public', 'GET', $params, null, null, array());
    }
    public function public_get_api_v2_3_trades($params = array()) {
        return $this->request('api/v2.3/trades', 'public', 'GET', $params, null, null, array());
    }
    public function publicspot_get_api_v3_2_market_summary($params = array()) {
        return $this->request('api/v3.2/market_summary', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicspot_get_api_v3_2_ohlcv($params = array()) {
        return $this->request('api/v3.2/ohlcv', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicspot_get_api_v3_2_price($params = array()) {
        return $this->request('api/v3.2/price', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicspot_get_api_v3_2_orderbook_l2($params = array()) {
        return $this->request('api/v3.2/orderbook/L2', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicspot_get_api_v3_2_trades($params = array()) {
        return $this->request('api/v3.2/trades', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function private_get_api_v2_3_user_wallet($params = array()) {
        return $this->request('api/v2.3/user/wallet', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_api_v2_3_user_wallet_history($params = array()) {
        return $this->request('api/v2.3/user/wallet_history', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_api_v2_3_user_open_orders($params = array()) {
        return $this->request('api/v2.3/user/open_orders', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_api_v2_3_user_positions($params = array()) {
        return $this->request('api/v2.3/user/positions', 'private', 'GET', $params, null, null, array());
    }
    public function private_get_api_v2_3_user_trade_history($params = array()) {
        return $this->request('api/v2.3/user/trade_history', 'private', 'GET', $params, null, null, array());
    }
    public function private_post_api_v2_3_order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_api_v2_3_user_wallet_transfer($params = array()) {
        return $this->request('api/v2.3/user/wallet/transfer', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_api_v2_3_leverage($params = array()) {
        return $this->request('api/v2.3/leverage', 'private', 'POST', $params, null, null, array());
    }
    public function private_post_api_v2_3_position_mode($params = array()) {
        return $this->request('api/v2.3/position_mode', 'private', 'POST', $params, null, null, array());
    }
    public function private_put_api_v2_3_order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'PUT', $params, null, null, array());
    }
    public function private_delete_api_v2_3_order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'DELETE', $params, null, null, array());
    }
    public function publicGetApiV23MarketSummary($params = array()) {
        return $this->request('api/v2.3/market_summary', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetApiV23Ohlcv($params = array()) {
        return $this->request('api/v2.3/ohlcv', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetApiV23Price($params = array()) {
        return $this->request('api/v2.3/price', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetApiV23Orderbook($params = array()) {
        return $this->request('api/v2.3/orderbook', 'public', 'GET', $params, null, null, array());
    }
    public function publicGetApiV23Trades($params = array()) {
        return $this->request('api/v2.3/trades', 'public', 'GET', $params, null, null, array());
    }
    public function publicSpotGetApiV32MarketSummary($params = array()) {
        return $this->request('api/v3.2/market_summary', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicSpotGetApiV32Ohlcv($params = array()) {
        return $this->request('api/v3.2/ohlcv', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicSpotGetApiV32Price($params = array()) {
        return $this->request('api/v3.2/price', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicSpotGetApiV32OrderbookL2($params = array()) {
        return $this->request('api/v3.2/orderbook/L2', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function publicSpotGetApiV32Trades($params = array()) {
        return $this->request('api/v3.2/trades', 'publicSpot', 'GET', $params, null, null, array());
    }
    public function privateGetApiV23UserWallet($params = array()) {
        return $this->request('api/v2.3/user/wallet', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetApiV23UserWalletHistory($params = array()) {
        return $this->request('api/v2.3/user/wallet_history', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetApiV23UserOpenOrders($params = array()) {
        return $this->request('api/v2.3/user/open_orders', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetApiV23UserPositions($params = array()) {
        return $this->request('api/v2.3/user/positions', 'private', 'GET', $params, null, null, array());
    }
    public function privateGetApiV23UserTradeHistory($params = array()) {
        return $this->request('api/v2.3/user/trade_history', 'private', 'GET', $params, null, null, array());
    }
    public function privatePostApiV23Order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostApiV23UserWalletTransfer($params = array()) {
        return $this->request('api/v2.3/user/wallet/transfer', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostApiV23Leverage($params = array()) {
        return $this->request('api/v2.3/leverage', 'private', 'POST', $params, null, null, array());
    }
    public function privatePostApiV23PositionMode($params = array()) {
        return $this->request('api/v2.3/position_mode', 'private', 'POST', $params, null, null, array());
    }
    public function privatePutApiV23Order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'PUT', $params, null, null, array());
    }
    public function privateDeleteApiV23Order($params = array()) {
        return $this->request('api/v2.3/order', 'private', 'DELETE', $params, null, null, array());
    }
}
